### ISSUE TITLE
max width

### ISSUE THREAD

**Issue by inifaisal** [sugarshin/react-instagram-embed#2]
cannot set width, always overrided.

**Comment by sugarshin** [comment]
Hi, Thank you for this issue. Please tell me more info, also can you post code to this ?

**Comment by eltongonc** [comment]
This issue also occurs with me.  I've set the max-width to 815px. When it is loading the post it is 815px, but when it is done loading it becomes smaller.

Example code:
```
<InstagramEmbed
   url={this.props.data['igtv_url_' + this.state.id]}
   maxWidth={815}
   hideCaption={true}
   containerTagName='div'
   injectScript
   protocol=''
   onLoading={() => {}}
   onSuccess={() => {}}
   onAfterRender={() => {}}
   onFailure={() => {}}
/>
```

Screenshot loading: 
![image](https://user-images.githubusercontent.com/14180132/61797134-1b826a00-ae27-11e9-9bc5-70199795f4a2.png)

Screenshot done loading:
![image](https://user-images.githubusercontent.com/14180132/61797407-a4010a80-ae27-11e9-9ecc-cfa5a3bc9b15.png)

**Comment by tylerjbainbridge** [comment]
@eltongonc did you ever figure this out?

**Comment by eltongonc** [comment]
@tylerjbainbridge unfortunately not. The project I was using this for also stopped, so no alternative as well
