### ISSUE TITLE
Instagram API deprecation

### ISSUE THREAD

**Issue by aakashbajaj** [sugarshin/react-instagram-embed#225]
> UPDATE
March 30, 2020 Update: We understand these are challenging times for our developer community, so we are postponing disabling the Instagram Legacy API Platform by 90 days to June 29, 2020. Remaining endpoints on the Legacy API will no longer be available after this date and your app's users may lose functionality. 
We urge you to migrate to the Instagram Graph API  and the Instagram Basic Display API  without delay so that users of your app have time to transition as well. Both APIs rely on permissions that require App Review , which can take a week or longer to complete, so you should begin the process as soon as you can to avoid any interruption in service. Please see this blog post  for tips on getting through our App Review process. 
If you're only using the Legacy API to generate tokens in order to display your Instagram Feed on a personal website, you can use the Instagram Basic Display API's User Token Generator  to continue generating tokens. The User Token Generator does not require App Review, but it will only work for your owned Instagram accounts (i.e. accounts for which you know the login credentials). Refer to the developer documentation  to learn more.

Will the library still work after the above mentioned change?

**Comment by iaarnio** [comment]
I'm just a user of this library but this Instagram API deprecation does not seem to affect this library.  This library uses embedding API which is to be still valid:  https://developers.facebook.com/docs/instagram/embedding/

**Comment by phil-monroe** [comment]
I'm actually not a user of this library, but it seems that Facebook is indeed deprecating the embed endpoint that this library is using on October 24, 2020.

https://developers.facebook.com/docs/instagram/oembed-legacy

While it looks like it would likely be a simple change to uptake the new OEmbed endpoint, it will require a configured Client Access Token with the requests.

https://developers.facebook.com/docs/instagram/oembed/

**Comment by iaarnio** [comment]
I checked the code and this library is using the deprecated API endpoint:

```
src/index.tsx:
private fetchEmbed(queryParams: string): void {
    this.request = this.createRequestPromise(`https://api.instagram.com/oembed/?${queryParams}`);
```

Using this API endpoint and the query parameter `breaking_change=oembed` will result '400 bad request' response.
Also the API endpoint prints out `This endpoint is deprecated. Please read https://developers.facebook.com/docs/instagram/oembed  to learn how to migrate your endpoint.`

The new API endpoint would be `https://graph.facebook.com/v8.0/instagram_oembed/`
However, switching to this new API endpoint is a breaking change as it requires `access_token` to work. 
Library user would need to provide it as an URL parameter.

**Comment by iaarnio** [comment]
There is now PR for this API change too: https://github.com/sugarshin/react-instagram-embed/pull/242

**Comment by iaarnio** [comment]
Live demo (https://sugarshin.github.io/react-instagram-embed/) of this library is now returning 400 error. 

![image](https://user-images.githubusercontent.com/8036867/97158782-93ee7e00-1782-11eb-9755-332e62d94a20.png)

@sugarshin, any possibility to merge the PR to fix issues people are having with the deprecated API?

**Comment by sugarshin** [comment]
solved: https://github.com/sugarshin/react-instagram-embed/pull/242
