### ISSUE TITLE
Looks like this no longer works

### ISSUE THREAD

**Issue by davidrhoderick** [sugarshin/react-instagram-embed#235]
The demo URL at https://sugarshin.github.io/react-instagram-embed/ doesn't show me any images and when I change the embed URL I get a "this.request is null" error.

**Comment by fantapop** [comment]
Working for me now

**Comment by danielotieno** [comment]
It doesn't work for me

**Comment by fvedoin** [comment]
It isn't working here too. I'm with the following error: SyntaxError: Unexpected token T in JSON at position 0, but it was working last week.

**Comment by zeroone-c** [comment]
Having the same issue too! It only happened recently

**Comment by fantapop** [comment]
See this thread: https://github.com/sugarshin/react-instagram-embed/pull/242

**Comment by sugarshin** [comment]
solved
