### ISSUE TITLE
can't install this package

### ISSUE THREAD

**Issue by ksyp-7** [sugarshin/react-instagram-embed#255]
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: instagram-clone@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^15.0.0 || ~0.14.0" from react-instagram-embed@2.0.0
npm ERR! node_modules/react-instagram-embed
npm ERR!   react-instagram-embed@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-20T11_18_25_291Z-debug.log`

**Comment by ZacchNaa** [comment]
Same issue here please. Really need help.

npm i react-instagram-embed
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: instagram-clone@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0 || ^15.0.0 || ~0.14.0" from react-instagram-embed@2.0.0        
npm ERR! node_modules/react-instagram-embed
npm ERR!   react-instagram-embed@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Tranquil\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tranquil\AppData\Local\npm-cache\_logs\2021-03-06T13_35_10_864Z-debug.log

**Comment by ZacchNaa** [comment]
I did a force install but it looks like the functionality is broken or something....

**Comment by itsanishmv** [comment]
> I did a force install but it looks like the functionality is broken or something....

same issue

**Comment by sugarshin** [comment]
https://github.com/sugarshin/react-instagram-embed/issues/271
