### ISSUE TITLE
styling 

### ISSUE THREAD

**Issue by Jaikant** [sugarshin/react-instagram-embed#8]
Hey, thanks for the nice component. Plugging it in was pretty pretty simple and it worked flawlessly. Just one small thing, the styling I am seeing is a little different from the demo.
1. I am not getting the instagram logo which is at the bottom
2. The follow button doesn't have the box around it.
3. The number of weeks old doesn't show. 
I checked out the example code and didn't find any css in there which I could use.

Btw, I am doing server side rendering.

![instagram](https://cloud.githubusercontent.com/assets/3472565/22876779/58ad1be8-f1f8-11e6-8e5d-378701bf7a07.jpg)

**Comment by sugarshin** [comment]
Thanks for this issue. I will check later next few days.

**Comment by sugarshin** [comment]
Sorry for late reply.

- You can't styling to embedded element
- SSR not supported
